"""add_enable_trading_nonce_timestamp

Revision ID: 04c0e360ddb4
Revises: f1ef19aa4f90
Create Date: 2025-12-13 03:37:15.349469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c0e360ddb4'
down_revision = 'f1ef19aa4f90'  # Points to previous migration
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('enable_trading_nonce', sa.String(), nullable=True))
    op.add_column('users', sa.Column('enable_trading_timestamp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'enable_trading_timestamp')
    op.drop_column('users', 'enable_trading_nonce')
    # ### end Alembic commands ###

