"""add_polymarket_wallet_address

Revision ID: ef997d80f2cb
Revises: 04c0e360ddb4
Create Date: 2025-12-13 06:48:05.887077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef997d80f2cb'
down_revision = '04c0e360ddb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('polymarket_wallet_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'polymarket_wallet_address')
    # ### end Alembic commands ###

