"""add_clob_api_creds_to_user

Revision ID: f1ef19aa4f90
Revises: dfbd0b293b91
Create Date: 2025-12-09 16:46:38.594160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ef19aa4f90'
down_revision = 'dfbd0b293b91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clob_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('clob_api_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('clob_api_passphrase', sa.String(), nullable=True))
    op.add_column('users', sa.Column('trading_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trading_enabled')
    op.drop_column('users', 'clob_api_passphrase')
    op.drop_column('users', 'clob_api_secret')
    op.drop_column('users', 'clob_api_key')
    # ### end Alembic commands ###

